### PR TITLE
Completely changed story, added a kitchy pic of the sun

### PR DESCRIPTION
**Pull request by floridop**
Added some content to your story. You are free to ask me to do any change you like before approving! Use this opportunity to experiment.

To complete this task you need to merge my contribution as explained in slides 84 to 89 keeping in mind that you are the release manager.

### CODE REVIEW

**Comment by imgmaterial** [comment]
Could you tie the original character, _princess_ into the changed story? Thank you in advance!

**Comment by floridop** [comment]
Ok will do!

**Comment by floridop** [comment]
While trying to revert, I stumbled upon what it looks like a git bug, this was interesting... Will post about it later

**Comment by floridop** [comment]
Turns out I was doing revert wrong, happens to teachers as well :)
In the end I decided not to revert as you asked me to factor in the princess again, so I put her under the sun. How about this? Admittedly the sun is a bit too big.

**Comment by imgmaterial** [comment]
This looks good to merge

**Comment by floridop** [comment]
I'll close this part of the homework, but if there is something else you're
curious to try and I am available I'll be happy to test.

**Pull request merged**
